### ISSUE TITLE
06/10/2020 - Design Updates

### ISSUE THREAD

**Issue by werzl** [k8-proxy/p-ui-wireframes#52]
## Description
We have an updated design document, capture a list of updates for the UI by scanning the doc and noting down any feature changes.

### Design Updates 
<table>
<thead>
<tr>
  <th>Design Doc</th>
  <th>SOW</th>
  <th>Page on the UI</th>
  <th>Changes</th>
</tr>
</thead>

<tbody>
<tr>
  <td>1.4.2.1 - Transaction Log Description</td>
  <td>3.2.4</td>
  <td>Request History</td>
  <td>
    Show all possible transaction risk levels:
    <br/>- Safe
    <br/>- Policy Blocked
    <br/>- Policy Allowed
    <br/>- Blocked by NCFS
    <br/>- Allowed by NCFS
  </td>
</tr>
<tr>
  <td>1.4.4.1 Policy Management Description</td>
  <td>3.2.2</td>
  <td>Policy</td>
  <td>
    Add Action Configuration Items
    <br/>- Glasswall Un-Managed Filetype
    <br/>- Glasswall Blocked Filetype
    <br/>Both should have the following options in a drop-down list:
    <br/>- “Relay” – the document should be relayed unmodified
    <br/>- “Block” – the document should be blocked
    <br/>- “Refer” – the document should be referred to the NCFS for a decision
  </td>
</tr>
<tr>
  <td>1.4.6.1 - File Drop System - Description</td>
  <td>3.2.5</td>
  <td>File Drop</td>
  <td>Add some descriptive text explaining that the SDK policy has everything set to 'sanitise'</td>
</tr>
</tbody>
</table>

### Questions
1. Transaction Log File Info Modal ...This feature shall also allow users to see which policies were applied to non-compliant files.

Is this covered by the "Content Management Policy Details" section in the modal on slide 17? This would be similar to Rebuild for Email, showing only the content management flags that affected the rebuild, not the entire policy.
![image](https://user-images.githubusercontent.com/16911902/95193225-62117980-07cb-11eb-8184-cf01729ad268.png)

<hr/>

2. Transaction Log
The 'Active Policy' column in the table - what are we showing here? A link to the policy / modal pop up showing the policy?

<hr/>

3. User Management
Have we decided there will be admin and non-admin users? Do we need to define privileges?

<hr/>

4. File Drop service
Just to confirm - there will be a file drop UI in the management portal that calls an API? 
  The other file drop for users without access to the management portal will have a separate UI for the file drop?

**Comment by BigPeeg** [comment]
1.4.2.1 - Transaction Log Description

- This needs to include `Allowed: Allowed by Non-compliant File Service`

1.4.2.1 - Transaction Log Description

- `Add a column for Active Policy` the active policy is only required on the details page, no need to add a column to the Request History page

**Comment by werzl** [comment]
> 1.4.2.1 - Transaction Log Description
> 
> * This needs to include `Allowed: Allowed by Non-compliant File Service`
> 
> 1.4.2.1 - Transaction Log Description
> 
> * `Add a column for Active Policy` the active policy is only required on the details page, no need to add a column to the Request History page

Done.
